name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Run tests
      run: bun test
    
    - name: Build binaries
      run: |
        bun run build:linux
        bun run build:macos
        bun run build:macos-arm
        bun run build:windows
    
    - name: Compress binaries
      run: |
        cd dist
        tar -czf devenv-linux-x64.tar.gz devenv-linux-x64
        tar -czf devenv-macos-x64.tar.gz devenv-macos-x64
        tar -czf devenv-macos-arm64.tar.gz devenv-macos-arm64
        zip devenv-windows-x64.zip devenv-windows-x64.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
        body: |
          ## Installation
          
          ### macOS/Linux
          ```bash
          # Download for your platform and extract
          tar -xzf devenv-*.tar.gz
          sudo mv devenv-* /usr/local/bin/devenv
          chmod +x /usr/local/bin/devenv
          ```
          
          ### Windows
          Download the zip file, extract, and add to PATH.
          
          ## Usage
          ```bash
          devenv scan
          devenv scan -o config.json -f json
          devenv scan -f script -o setup
          ```